language: ruby
rvm:
- 2.2.2
before_script: gem install jekyll
script: jekyll build --destination out
notifications:
  flowdock:
    secure: l+r/RXhjPsNZMhH4e/99hqTYX5FGewYsyKU8NQE0D+59MrqhCHO8LKt4AAb/mCCX2zVONji+z4M6HVCqn+Ypu6Ssv3YzgB8P/fqxnoYRbAcZU7DFTCAt9C3wmOrjAEbmb+OpzSYbiba2AyTkl7rEqtV07ByXlb36J3oaPD+tpzF90riWqvt0pNPtmGmEob005Qoiw9ilrKVkdPp9Jn4606Wfh9EzcArojAdtTyQmMetvQBVDf9PdUNipYNVTGcooXEek38RZ1eTur3bNf4MtG06nBiQ4AM8PC6TmSBoSPQ0o+vONHSnMwItGStNF2U/CXDqgniVujBeMmd5hvp0TJPgdawH0/K6hoc6lgMPV8rU633Uxs7zfJqSQIlZqJ9i3Z7eVjfDEWAYxs719/+NX1jpsc5Ew2moHrOqY4U28R3S6wtRdPzULDNy+VR+yLsjnN/EQlZ3yG2Mb8AQiwZ+lkmHdcMI7SuFGvq2ZHloFZj6gZ4KimeQwKshKRzyUNT02DnCN2H1Qiq1qvLLjHEpeV3SMv+Jx26BPDHNChPY7IwOsV4G4Kv/OD7o8IwfP7ps64WH52BZ9cyEIA96bTOiDeSkxhKfH5ii71hjwVAsCdQMVLROclxrpI6kWgGIYg6vbA/LzxwxhQGPMu0dP/k/uX4pEdoMdAKidoOQUjQ0wSG4=
deploy:
  provider: s3
  bucket: landing.stockflare.com
  skip_cleanup: true
  local-dir: out
  edge: true
  region: us-east-1
  endpoint: s3-us-east-1.amazonaws.com
  on:
    branch: master
  secret_access_key:
    secure: L92WMoeGEROKxK5bjB8RYYe2K9Vgqy/Bl+lUjLzJV+oWe71JVP4AvKC86IgfMNhYoAPpHmPF5qyNGJfh4gnhI8n3qjZxDdJfG9CGtNKo41P5Z029cS9B9Cfbp44vZg3G8cwLN8Qj1Pc7bmDcFuCiSLeZ80UOwVlKnOIL6Pulr78O0NqaT0AKylJKuVeP9zaErOc2+D24+fNjAKgzO3h1GKnoltj3B7IREzbAku0IGxJQ240bY/8hYZOJdbVY488XnDP1DaM5oEjXOpBUaq/c0PO+0E4o27GfKt/GAH/0V11+iFHqYPH8Ej0edVZZqDdTqyDLF3KRDPUo1zqCZ9iDtqsZsIRepPIzab/1GgR6jM21PAGZNck6uz+k/2nQYrqv+e5ahiHFvWXcJGNMH3gEI20OeOGq8XPSY+rJSW2gUPQZEPUTY19+JgOPu5l2pHBuZRjymj2RhBUhAg8MrAkZt+EOlhD8nLsyuvg3S3zEqSYnvp35tYWiA7hz5ZWwWhj69f0kNpCFw9HZJHLnkXvv2QvB0yQcRJsfcq1ugVC0SxeCVq2untCVDBVQ6qQzQj+Hv6R69Nh/EYHLrCPqO1Wv/D/1H5JXr8SNi9rjYDcUe4POlTAmsCdHX5/sjX16skOxRkwsCd0zurqT7qHG92qg7AlD42zad+a1cFu5cNEn+0Y=
  access_key_id:
    secure: hyyuuS6B2EmMmOcrPVtPivZPOhbH7+L9YoQ6XxD98zcTl1CM0sOHd6d0o5VxApVCJ7u4Lnx6Na3ogNsXYg8YKan98iEIn9vFPunSBdAe8CGNt260TSKXv6IqYPZQvEFjH6LcY1/qpkEoKet/O/MvyGt4AngPVBF9xc1H1EzFGHGp1XMnan1tXri03Qsp5EITlhVwZFIr8b6pVdhRspzK6bCJrarsawFgNJsD/R8R4dEzLF+SxYkBFvJO8maQkmNbytNBBVFZjTUxCYyM2C/p4f6g/uQ7ar7gMitKa28UYSghd8+vYOMWqpkCeB/ka3SZ6TepXN5chsTwTYDbqstJOcxtmG3RgG0WGSN4wqUcfVzPwxb6sN8ddQCw4RCOk9wGak2+32lg1mbIVaXr17X5r85rpJY8yCeBoszS1znKU0KhpCckQoD+Q7XXoY5I9Z0U4M9XQKhaDSDC1dFkelnP1XIlrpoTGE5eoNaNeKacpEffckYY2TTfwMF3AQGS2JHWn/GxeJdTsoSNsVu0zHfAzMJqC/GzSOpa4IEg1A87YNGzURpNbB/yLu6b4CDORHKe4dcw1B2j4i36EJRi/R7XAjk56bX5txvLYZ09ZDUj/aiwkY8UfEnWtAyUmb8T0xKRQ2UgnFp3FTpgWrsM0wkhFSDAFo5Aplzt4F3oBZkAWUs=
