language: ruby
rvm:
- 2.2.2
before_script: gem install jekyll
script: jekyll build --destination out
notifications:
  flowdock:
    secure: jLZJboEvTapLx4Ax7BG+yKCR0Zv7ytut7lMhgLG4IQ+3k5GZcri7BMga6Nx3+R5xF5SajWNN4oHlQ4qlOpBfpwZ/WiGVzSfBjBnuhNYCngk8/jmK9RkGs0lSSIh2C+LyyDX8ecSqOHbdeE71dEF0I2Wsbi2gflWe16TE4b79X4Tnz6yF4f/QxRiZ6AgleGx5u/m3XIMl9LcS7gyNQ3b3FBExAA3V3Njh2hY5igqX8adHGbnr929PpGP6bT29Qqwjti6WBuG5BaVlGIesTpVVvV7kpRf8IkbIEk937aUpBjqsbV19MeozMqMgNyYWJOIaUbv4YO43/lB72GrO9IDyvD5uhN1GSqidS02UJhXnw7vsIa5navBMVqT5s403sIkCZembUDn8k3fwQWL2tkb+7QS799J/wqlR7MtmjOtuyQeZqNCyc/42rqpy3PywKJKaJyqdNMlY/XARM64nSqUSzH41L9QXeB87eMzrzhqaw6NJ9//yd7C6ALys1IAOtbp3xc8VRdoMa1mNMeZghkd7NxN0GvRfpOPNH3xRDRMYch6RUKz8gw0YOgY6pqqSK+k6JICe6aZzDkInUVg73uANI92UMDl3TRl3ICh83Apcg8EcbWFBG7xmo8V7uIMbrBi5i+ITe9dD25w6lP5GfLGJt7RJTIp/JSR7gfiAjQbUaOg=
deploy:
  provider: s3
  bucket: landing.stockflare.com
  skip_cleanup: true
  local-dir: out
  edge: true
  region: us-east-1
  endpoint: s3-us-east-1.amazonaws.com
  on:
    branch: master
  secret_access_key:
    secure: sZwpwLp7e7JhCgq3Y2hfbVwAsgc1bU2rkbxn07UG2J0+9D20miJyzLhixDu3acesGxZGnYMq3NRobIGhLskR+abYgwqIviW+0ltZYr4bOENgL/nNvjMnIJIBk8fXZAOQHCGnVc/lXIwiOAncb/ioVnP5zj1R2c3qa3NYDy3QiazKwTyQyZfbuUqT0G1L+5bBRnHbYBHZPAjl6s+4uVvdVSJ5lsEnuEIQDbY0D+PreLUOz1f1Mw7S15oIy946vVjQYJXgUdgB0FuR/W2/hR+3I2s6iOUDl/JReHuvS37ZxQneZ3hr2iI6M77ogKfKqS9dNwrfLjiDLg1v6jb+1tBzfs6PJr/2GTHpRS4v7eY0ViosZN+i5foFRu/5R4JV1C8EtX/fCQYi+1vWa1vTh1x96HdAYUThSDv6LIZfDMC+oZKZWrIbm7Ca237VC4pqnEdoCLPNMUDS0tm9sIrtMze39eVH7Sgw/aeCs1oghuYVnBJXfMKdeWjhJCxXkVGmu8+bRMDU4E5pCZGQW0z9LiWYLB50x0gbcmwFbAhxvAia2ZIOyGL6gIrIVvweqfn14I1YoxxorqAcuwQ7+D164PlulKVdmjoJVMpsMDE72pCdqaufdtjuUmDBUfYyfpB4KnP/4v+R9mpyv4viyhANEg9m9L9r4IPCBUzcbZ8X5dN+pVc=
  access_key_id:
    secure: gmvkXUz5Z0GtRgFJmDxHcYYMqCcCYNKoBdT9k9kvm5CAUD2LAve8iH25qkNHaxAxXZZlOAA5v4wmBY0etoUzThiUyRyGoZ9W+VvOlviiQ6xbWnxSzjhtzvOHJdDazoomzsLBGvfGNZZUCmM+NtR4FWocTAnos9AUGO0SXx6gntUQk/CgtQyrPxrmL/tA58iQqNPaD/wf4Bswj6eieUgE1ryjd3lfEn4/gqJKzdmJYut9/pEC5ik9veDnFVYzBR7kx/ScVvNZDXTNoApfJKwolcglU9pZSL7MFe1QZ2A7XuTJZi9myNv9gyyhleCd4E22sX8hr2CCNyr+rZR7MmnCyiA8ZSpA5/vzFet/JYPonIxBzBo6hsRfYd+VvEEKkU0MEM2l/TDHhJyT2w6SWtKbLUGS/0Yi7eWAkJxjqVxYolC60tnkYpzgeVbMUR3yM8hTkYIQiNUbeMSb/KZy2NrOqg+lik2e5C8hHvEFRVLafBEJoDNodFF851kuEhpc8EGXgrjsGN8KKnYQIUxA4H4FwKvmYNwr5RDYnEiwat5gnTPqxr/4NcOUKGB8RbRaeJ2A0OE/OlNy2JKGIPcQrDOiWVrfR6QjKjb60FlAdsuXP5ICqLSMSmk/SKpZwQMgPmjvkXcCo611TNnFDoiLLb5VzxGTf5be7Xu8KbQWAV6F/wY=
